version: 0.2
phases:
 install:
   commands:
     - echo "install step"
     - gem update --system --quiet
     - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
     - echo "jekyll installed"
     - gem uninstall bundler
     - gem install bundler
     - bundle install
     - echo "bundle installed"
 build:
   commands:
     - echo "building step"
     - bundle exec jekyll build --verbose
     - echo "building complete"
     - find _site/ -type f ! -iname 'index.html' -iname '*.html' -print0 | while read -d $'\0' f; do mv "$f" "${f%.html}"; done
     - echo "file extensions removed"
 post_build:
   commands:
     - echo "post_build step"
     - aws cloudfront create-invalidation --distribution-id E1BBD9XD38EPQC --paths /*
     - echo "CDN cache invalidated"
     - cd _site/
     - aws s3 sync --delete . s3://galenballew.fyi 
     - echo "website sinked to bucket"
