version: 0.2
phases:
 install:
   commands:
     - echo "install step"
     - gem update --system --quiet
     - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
     - echo "jekyll installed"
     - gem uninstall bundler
     - gem install bundler
     - bundle install
     - echo "bundle installed"
 build:
   commands:
     - echo "building step"
     - bundle exec jekyll build --verbose
     - echo "building complete"
 post_build:
   commands:
     - echo "post_build step"
     - aws s3 sync --delete _site/ s3://galenballew.fyi/
     - echo "files transferred successfully"
     - aws cloudfront create-invalidation --distribution-id E1BBD9XD38EPQC --paths "/*"
     - echo "CDN cache invalidated"